export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const CREATE_IMAGE_SUCCESS = "CREATE_IMAGE_SUCCESS";
export const UPDATE_IMAGE_SUCCESS = "UPDATE_IMAGE_SUCCESS";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
